#!/bin/sh
SOURCE=$0
while [ -h "$SOURCE" ]; do
	DIR=$(cd -P "$(dirname "$SOURCE")" && pwd)
	SOURCE=$(readlink "$SOURCE")
	case $SOURCE in
	/*) ;;
	*) SOURCE=$DIR/$SOURCE ;;
	esac
done
DIR=$(cd -P "$(dirname "$SOURCE")" && pwd)
CLI=$DIR/../dist/cli.js

exec node "$CLI" "$@"
